/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import Koneksi.koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
/**
 *
 * @author Satrio_Ganteng
 */
public class View_Menu extends javax.swing.JFrame {
private static final long serialVersionUID = 1L;
java.util.Date tglsekarang = new java.util.Date();
private SimpleDateFormat smpdtfmt = new SimpleDateFormat("EEEE,dd MMMMMMMMM yyyy",new java.util.Locale("id"));
private String tanggal = smpdtfmt.format(tglsekarang);
private Connection conn = new koneksi().connect();
    /**
     * Creates new form View_Menu
     */
    public View_Menu() {
        initComponents();
        setDefaultCloseOperation(0);
        this.setTitle("MENU UTAMA");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
        txttanggal.setText(tanggal);
        setjam();
    }
public final void setjam(){
    ActionListener taskPerformer = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
        String nol_jam = "",nol_menit="",nol_detik="";
        
        java.util.Date dateTime = new java.util.Date();
        int nilai_jam = dateTime.getHours();
        int nilai_menit = dateTime.getMinutes();
        int nilai_detik = dateTime.getSeconds();
        
        if (nilai_jam <=9) nol_jam="0";
        if(nilai_menit <=9) nol_menit="0";
        if(nilai_detik <=9) nol_detik="0";
        
        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit + Integer.toString(nilai_menit);
        String detik = nol_detik+ Integer.toString(nilai_detik);
        
        txtjam.setText(jam+":"+menit+":"+detik+"");
        }
    };
    new Timer(1000,taskPerformer).start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnPedaftaran = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnsiswa = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        ljmlguru = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        ljmlmatpel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        Ljmlhsiswabaru = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        ljmlsiswa = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txttanggal = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtjam = new javax.swing.JLabel();
        txtnmaplikasi = new javax.swing.JLabel();
        txtnmaplikasi1 = new javax.swing.JLabel();
        txtnmaplikasi2 = new javax.swing.JLabel();
        txtnmaplikasi3 = new javax.swing.JLabel();
        txtnmaplikasi4 = new javax.swing.JLabel();
        txtnmaplikasi5 = new javax.swing.JLabel();
        txtnmaplikasi6 = new javax.swing.JLabel();
        txtnmaplikasi7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logo2.png")).getImage());

        jPanel3.setBackground(new java.awt.Color(255, 102, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Showcard Gothic", 3, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 102));
        jLabel23.setText("MENU.....");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8_Logout_Rounded_Down_32px.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 40, -1));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPedaftaran.setBackground(new java.awt.Color(255, 102, 0));
        btnPedaftaran.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPedaftaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPedaftaranMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-checklist-filled-20.png"))); // NOI18N
        jLabel7.setText("Buatkan Admin");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnPedaftaranLayout = new javax.swing.GroupLayout(btnPedaftaran);
        btnPedaftaran.setLayout(btnPedaftaranLayout);
        btnPedaftaranLayout.setHorizontalGroup(
            btnPedaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPedaftaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPedaftaranLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(38, 38, 38))
        );
        btnPedaftaranLayout.setVerticalGroup(
            btnPedaftaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPedaftaranLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.add(btnPedaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 70));

        btnsiswa.setBackground(new java.awt.Color(255, 102, 0));
        btnsiswa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnsiswaMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-writer-male-20.png"))); // NOI18N
        jLabel8.setText("Password Admin");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnsiswaLayout = new javax.swing.GroupLayout(btnsiswa);
        btnsiswa.setLayout(btnsiswaLayout);
        btnsiswaLayout.setHorizontalGroup(
            btnsiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnsiswaLayout.createSequentialGroup()
                .addGroup(btnsiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnsiswaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(btnsiswaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel8)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        btnsiswaLayout.setVerticalGroup(
            btnsiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnsiswaLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.add(btnsiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-school-director-100.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 110, 110));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel33.setText("ADMIN MASTER");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 190, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/150 x 150.png"))); // NOI18N
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(230, 81, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(" GURU");
        jLabel24.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jPanel6.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 270, 40));

        ljmlguru.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ljmlguru.setForeground(new java.awt.Color(255, 255, 255));
        ljmlguru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ljmlguru.setText("JUMLAH");
        ljmlguru.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ljmlguruAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel6.add(ljmlguru, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 270, 150));

        jPanel7.setBackground(new java.awt.Color(81, 45, 168));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("PROGRAM BELAJAR");
        jLabel25.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 270, 40));

        ljmlmatpel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ljmlmatpel.setForeground(new java.awt.Color(255, 255, 255));
        ljmlmatpel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ljmlmatpel.setText("JUMLAH");
        ljmlmatpel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ljmlmatpelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel7.add(ljmlmatpel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, 50));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 270, 150));

        jPanel8.setBackground(new java.awt.Color(213, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("SISWA BARU");
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 21, 270, 40));

        Ljmlhsiswabaru.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Ljmlhsiswabaru.setForeground(new java.awt.Color(255, 255, 255));
        Ljmlhsiswabaru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ljmlhsiswabaru.setText("JUMLAH");
        Ljmlhsiswabaru.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                LjmlhsiswabaruAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel8.add(Ljmlhsiswabaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, 50));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 270, 150));

        jPanel9.setBackground(new java.awt.Color(0, 51, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("SISWA AKTIF");
        jLabel22.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 270, 40));

        ljmlsiswa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ljmlsiswa.setForeground(new java.awt.Color(255, 255, 255));
        ljmlsiswa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ljmlsiswa.setText("JUMLAH");
        ljmlsiswa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ljmlsiswaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel9.add(ljmlsiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 170, 50));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 270, 150));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, -1, 340));

        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 0, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 130, 10, 430));

        jPanel4.setBackground(new java.awt.Color(255, 102, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttanggal.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txttanggal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-planner-30.png"))); // NOI18N
        txttanggal.setText("Hari, Tanggal");
        jPanel4.add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel28.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 420, 10));

        txtjam.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-clock-30.png"))); // NOI18N
        txtjam.setText("Jam");
        jPanel4.add(txtjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtnmaplikasi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnmaplikasi.setText("Kel. Cilangkap, Kec. Tapos Depok, Jawa Barat 16415");
        jPanel4.add(txtnmaplikasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 280, 20));

        txtnmaplikasi1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtnmaplikasi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-map-marker-20.png"))); // NOI18N
        txtnmaplikasi1.setText("Alamat");
        jPanel4.add(txtnmaplikasi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        txtnmaplikasi2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtnmaplikasi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-monitor-20.png"))); // NOI18N
        txtnmaplikasi2.setText("Judul Aplikasi");
        jPanel4.add(txtnmaplikasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txtnmaplikasi3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnmaplikasi3.setText("Perancangan Sistem Aplikasi Pendaftaran Siswa");
        jPanel4.add(txtnmaplikasi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        txtnmaplikasi4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtnmaplikasi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-school-building-20.png"))); // NOI18N
        txtnmaplikasi4.setText("Mitra");
        jPanel4.add(txtnmaplikasi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtnmaplikasi5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnmaplikasi5.setText("biMBA AIUEO Depok");
        jPanel4.add(txtnmaplikasi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        txtnmaplikasi6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnmaplikasi6.setText("Telp.0815 8650 5372");
        jPanel4.add(txtnmaplikasi6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 400, 20));

        txtnmaplikasi7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtnmaplikasi7.setText("Perum Griya Telaga Permai Blok D-15 No. 1 Rt.009/Rw.019");
        jPanel4.add(txtnmaplikasi7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 400, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 430, 390));

        jLabel2.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("A");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 60, 50));

        jLabel5.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("I");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel29.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 204));
        jLabel29.setText("U");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 50, -1));

        jLabel30.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 204, 0));
        jLabel30.setText("E");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, 60));

        jLabel31.setFont(new java.awt.Font("Ravie", 0, 48)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 102, 0));
        jLabel31.setText("O");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setText("Home");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1080, 70));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/icons8-seesaw-100.png"))); // NOI18N
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin Keluar ?", "Warning", 2);
        if (dialogResult == JOptionPane.YES_OPTION) {
            System.gc();
            java.awt.Window win[] = java.awt.Window.getWindows();
            for (int i = 0; i < win.length; i++) {
                win[i].dispose();
                win[i] = null;
            }
            new View_Loginn().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPedaftaranMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedaftaranMousePressed
        new View_daftarAdmin2().setVisible(true);
        
    }//GEN-LAST:event_btnPedaftaranMousePressed

    private void btnsiswaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsiswaMousePressed
         new View_adminbaru().setVisible(true);
//        dispose();
    }//GEN-LAST:event_btnsiswaMousePressed

    private void ljmlguruAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ljmlguruAncestorAdded
        String sql = "select count(nama_guru) from guru";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String jumlah  = hasil.getString("count(nama_guru)");
                ljmlguru.setText(jumlah);
            }
        }catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_ljmlguruAncestorAdded

    private void ljmlmatpelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ljmlmatpelAncestorAdded
        String sql = "select count(nama_matpel) from matapelajaran where no between 1 and 9";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String jumlah  = hasil.getString("count(nama_matpel)");
                ljmlmatpel.setText(jumlah);
            }
        }catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_ljmlmatpelAncestorAdded

    private void LjmlhsiswabaruAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_LjmlhsiswabaruAncestorAdded
        String sql = "select count(nama_siswa) from pendaftaran";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String jumlah  = hasil.getString("count(nama_siswa)");
                Ljmlhsiswabaru.setText(jumlah);
            }
        }catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_LjmlhsiswabaruAncestorAdded

    private void ljmlsiswaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ljmlsiswaAncestorAdded
        String sql = "select count(nama) from siswa";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String jumlah  = hasil.getString("count(nama)");
                ljmlsiswa.setText(jumlah);
            }
        }catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_ljmlsiswaAncestorAdded

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
      new View_daftarAdmin2().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        new View_adminbaru().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ljmlhsiswabaru;
    private javax.swing.JPanel btnPedaftaran;
    private javax.swing.JPanel btnsiswa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel ljmlguru;
    private javax.swing.JLabel ljmlmatpel;
    private javax.swing.JLabel ljmlsiswa;
    private javax.swing.JLabel txtjam;
    private javax.swing.JLabel txtnmaplikasi;
    private javax.swing.JLabel txtnmaplikasi1;
    private javax.swing.JLabel txtnmaplikasi2;
    private javax.swing.JLabel txtnmaplikasi3;
    private javax.swing.JLabel txtnmaplikasi4;
    private javax.swing.JLabel txtnmaplikasi5;
    private javax.swing.JLabel txtnmaplikasi6;
    private javax.swing.JLabel txtnmaplikasi7;
    private javax.swing.JLabel txttanggal;
    // End of variables declaration//GEN-END:variables
}
